pid logs/balanceo2.pid;
events {
	worker_connections 1024;
}
http {
    upstream 3sitios{
        server 127.0.0.1:81 weight=6;
        server 127.0.0.1:82 weight=4;
    }
	server {
		listen 80;

		location / {
            proxy_pass http://3sitios;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
		}
	}
}
